version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_PORT: $DB_PORT
      POSTGRES_HOST: $DB_HOST
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  custom:
    driver: bridge
