"""empty message

Revision ID: 012fa28672f9
Revises: db1b51432baa
Create Date: 2023-10-16 00:38:57.417506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012fa28672f9'
down_revision = 'db1b51432baa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
