"""empty message

Revision ID: 1174a9063e0a
Revises: f78a3ad05361
Create Date: 2023-10-11 00:22:47.851564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1174a9063e0a'
down_revision = 'f78a3ad05361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
