"""empty message

Revision ID: 3c15e6e88da1
Revises: e988e93c2f81
Create Date: 2023-10-11 00:18:01.201730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c15e6e88da1'
down_revision = 'e988e93c2f81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'status')
    # ### end Alembic commands ###
