"""empty message

Revision ID: 43a2a2566d9d
Revises: d4306e4b39b7
Create Date: 2023-10-31 13:59:28.342211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a2a2566d9d'
down_revision = 'd4306e4b39b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'created_at')
    # ### end Alembic commands ###
