"""empty message

Revision ID: 6d306eda433e
Revises: 49d98079d28d
Create Date: 2023-10-25 18:14:02.442252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d306eda433e"
down_revision = "49d98079d28d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_staff", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_staff")
    # ### end Alembic commands ###
