"""empty message

Revision ID: 791e5083b7bd
Revises: 1174a9063e0a
Create Date: 2023-10-11 02:05:53.920701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791e5083b7bd'
down_revision = '1174a9063e0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('records', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'image')
    op.drop_column('records', 'comment')
    # ### end Alembic commands ###
