"""empty message

Revision ID: 855c6975eddc
Revises: 6d306eda433e
Create Date: 2023-10-28 14:40:28.159732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855c6975eddc'
down_revision = '6d306eda433e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
