"""empty message

Revision ID: d4306e4b39b7
Revises: 855c6975eddc
Create Date: 2023-10-31 13:58:47.157320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4306e4b39b7'
down_revision = '855c6975eddc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
