"""empty message

Revision ID: da048e6ebbf1
Revises: 791e5083b7bd
Create Date: 2023-10-11 22:41:05.036333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da048e6ebbf1'
down_revision = '791e5083b7bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'image')
    # ### end Alembic commands ###
