"""empty message

Revision ID: db1b51432baa
Revises: da048e6ebbf1
Create Date: 2023-10-15 20:23:53.302404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1b51432baa'
down_revision = 'da048e6ebbf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'author')
    # ### end Alembic commands ###
