"""empty message

Revision ID: f78a3ad05361
Revises: 3c15e6e88da1
Create Date: 2023-10-11 00:22:26.371372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78a3ad05361'
down_revision = '3c15e6e88da1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'price')
    # ### end Alembic commands ###
